### ISSUE TITLE
Heatmaps - ValueError: X has 20 features, but MinMaxScaler is expecting 1 features as input.

### ISSUE THREAD

**Issue by Schrolli91** [philipperemy/keract#137]
When i try to show the heatmap i get the following error:
```
conv2d (1, 32, 20, 32) 
Traceback (most recent call last):
  File "/.../keract_.py", line 46, in <module>
    keract.display_heatmaps(activations, digit, save=False, fix=True)
  File "/home/.../.local/lib/python3.8/site-packages/keract/keract.py", line 527, in display_heatmaps
    img = scaler.transform(img)
  File "/home/.../.local/lib/python3.8/site-packages/sklearn/preprocessing/_data.py", line 434, in transform
    X = self._validate_data(X, copy=self.copy, dtype=FLOAT_DTYPES,
  File "/home/.../.local/lib/python3.8/site-packages/sklearn/base.py", line 437, in _validate_data
    self._check_n_features(X, reset=reset)
  File "/home/.../.local/lib/python3.8/site-packages/sklearn/base.py", line 365, in _check_n_features
    raise ValueError(
ValueError: X has 20 features, but MinMaxScaler is expecting 1 features as input.
```

`display_activations()` (the commented line) works fine with the following code, but `display_heatmaps()` will fail:
```python
    pred = model.predict(digit)
    value = np.argmax(pred)
    print(value)

    activations = keract.get_activations(model, digit, layer_names=["conv2d"])

    # keract.display_activations(activations, save=False)
    keract.display_heatmaps(activations, digit, save=False, fix=True)
```

**Comment by philipperemy** [comment]
@Schrolli91 can you provide a snippet that I can execute and run to reproduce the error?
Just replace your data by some random matrices in numpy with `np.random`.

**Comment by Schrolli91** [comment]
Here is my snippet:

```python
import numpy as np
from tensorflow import keras
import keract

model = keras.models.load_model("2021_03_19-model-cnn-100.keras")
model.summary()

dig = np.random.random((1, 32,20, 3))
print(dig.shape)
pred = model.predict(dig)

activations = keract.get_activations(model, dig, layer_names=["conv2d"])
# keract.display_activations(activations, save=False) # <-- this will run
keract.display_heatmaps(activations, dig, save=False, fix=True) # <-- but this give an error, see below
```

And here the console:
```
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
batch_normalization (BatchNo (None, 32, 20, 3)         12
_________________________________________________________________
conv2d (Conv2D)              (None, 32, 20, 32)        896
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 16, 10, 32)        0
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 16, 10, 64)        18496
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 8, 5, 64)          0
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 8, 5, 64)          36928
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 4, 2, 64)          0
_________________________________________________________________
flatten (Flatten)            (None, 512)               0
_________________________________________________________________
dense (Dense)                (None, 512)               262656
_________________________________________________________________
dropout (Dropout)            (None, 512)               0
_________________________________________________________________
dense_1 (Dense)              (None, 11)                5643
=================================================================
Total params: 324,631
Trainable params: 324,625
Non-trainable params: 6
_________________________________________________________________
(1, 32, 20, 3)
2021-03-25 07:20:16.630135: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
conv2d (1, 32, 20, 32) 
Traceback (most recent call last):
  File ".../keract_.py", line 37, in <module>
    keract.display_heatmaps(activations, dig, save=False, fix=True)
  File "...\Python37\lib\site-packages\keract\keract.py", line 527, in display_heatmaps
    img = scaler.transform(img)
  File "...\Python37\lib\site-packages\sklearn\preprocessing\_data.py", line 435, in transform
    force_all_finite="allow-nan", reset=False)
  File "...\Python37\lib\site-packages\sklearn\base.py", line 437, in _validate_data
    self._check_n_features(X, reset=reset)
  File "...\Python37\lib\site-packages\sklearn\base.py", line 366, in _check_n_features
    f"X has {n_features} features, but {self.__class__.__name__} "
ValueError: X has 20 features, but MinMaxScaler is expecting 1 features as input.
```

**Comment by philipperemy** [comment]
@Schrolli91 can you replace `keras.models.load_model("2021_03_19-model-cnn-100.keras")` by the model definition or upload your model file somewhere?

**Comment by Schrolli91** [comment]
Of course - but i dont think thats model depended
[2021_03_19-model-cnn-100.zip](https://github.com/philipperemy/keract/files/6202695/2021_03_19-model-cnn-100.zip)

**Comment by philipperemy** [comment]
yeah but I need this file to reproduce your error ;)

**Comment by philipperemy** [comment]
@Schrolli91 I ran your code and I didn't have any problem at all.

```
/Users/premy/PycharmProjects/keract/venv/bin/python /Users/premy/PycharmProjects/keract/examples/hghfg.py
2021-04-01 11:33:38.709351: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-04-01 11:33:38.709676: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
batch_normalization (BatchNo (None, 32, 20, 3)         12        
_________________________________________________________________
conv2d (Conv2D)              (None, 32, 20, 32)        896       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 16, 10, 32)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 16, 10, 64)        18496     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 8, 5, 64)          0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 8, 5, 64)          36928     
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 4, 2, 64)          0         
_________________________________________________________________
flatten (Flatten)            (None, 512)               0         
_________________________________________________________________
dense (Dense)                (None, 512)               262656    
_________________________________________________________________
dropout (Dropout)            (None, 512)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 11)                5643      
=================================================================
Total params: 324,631
Trainable params: 324,625
Non-trainable params: 6
_________________________________________________________________
(1, 32, 20, 3)
2021-04-01 11:33:39.001970: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
conv2d (1, 32, 20, 32) 

Process finished with exit code 0
```

**Comment by philipperemy** [comment]
Here are my deps. Maybe try the latest keract?

```
Package                  Version   Location
------------------------ --------- -----------------------------------
absl-py                  0.11.0
appdirs                  1.4.4
astunparse               1.6.3
binary                   1.0.0
cachetools               4.1.1
certifi                  2020.6.20
chardet                  3.0.4
click                    7.1.2
coverage                 5.2.1
cycler                   0.10.0
flatbuffers              1.12
gast                     0.3.3
google-api-core          1.23.0
google-auth              1.23.0
google-auth-oauthlib     0.4.1
google-cloud-bigquery    2.3.1
google-cloud-core        1.4.3
google-crc32c            1.0.0
google-pasta             0.2.0
google-resumable-media   1.1.0
googleapis-common-protos 1.52.0
graphviz                 0.14.1
grpcio                   1.32.0
h5py                     2.10.0
idna                     2.10
joblib                   0.16.0
keract                   4.4.0     /Users/premy/PycharmProjects/keract
Keras-Preprocessing      1.1.2
kiwisolver               1.2.0
Markdown                 3.2.2
matplotlib               3.3.1
numpy                    1.19.4
oauthlib                 3.1.0
opencv-python            4.5.1.48
opt-einsum               3.3.0
pandas                   1.2.3
Pillow                   7.2.0
pip                      20.2.2
proto-plus               1.11.0
protobuf                 3.12.2
pyasn1                   0.4.8
pyasn1-modules           0.2.8
pydot                    1.4.1
pyparsing                2.4.7
pypinfo                  17.0.0
python-dateutil          2.8.1
pytz                     2020.4
requests                 2.24.0
requests-oauthlib        1.3.0
rsa                      4.6
scikit-learn             0.23.2
scipy                    1.4.1
seaborn                  0.11.1
setuptools               49.1.0
six                      1.15.0
tensorboard              2.4.0
tensorboard-plugin-wit   1.7.0
tensorflow               2.4.0
tensorflow-estimator     2.4.0
termcolor                1.1.0
threadpoolctl            2.1.0
tinydb                   4.2.0
tinyrecord               0.2.0
typing-extensions        3.7.4.3
urllib3                  1.25.9
Werkzeug                 1.0.1
wheel                    0.36.2
wrapt                    1.12.1
```

**Comment by Schrolli91** [comment]
I'll re-check this at the weekend and let you know what happend.
So far - Thanks for your efforts

**Comment by philipperemy** [comment]
@Schrolli91 good luck!

**Comment by philipperemy** [comment]
@VincenzoNucci thank you I'm going to re-open the issue.

**Comment by kknydnai** [comment]
Hello everyone I have solved the problem. It has to do with dependencies. 
I installed tensorflow, numpy, scikit-learn, scipy and keract to the ones mentioned by @philipperemy 
After that the code works like so: you need to get the first element of the image in the diplay_heatmaps() function. 

```
keract_inputs = X_train[3:4]
activations = get_activations(model, keract_inputs)
display_heatmaps(activations, keract_inputs[0], fix=False)
```

**Comment by VincenzoNucci** [comment]
@kknydnai You're right. I had different versions for scikit-learn and scipy. Downgrading both to the versions listed [here](https://github.com/philipperemy/keract/issues/137#issuecomment-811593800) worked.

It may be that the MinMaxScaler changed in version 0.24

Thank you all.

**Comment by philipperemy** [comment]
Oh yeah it seems I saw it before: https://github.com/philipperemy/keract/blob/dea741b7247a45b7c8efd3f8fe1bd84d609a9d81/examples/examples-requirements.txt#L4

**Comment by philipperemy** [comment]
```bash
scikit-learn<=0.23.2
```
Will solve this.

**Comment by qwertpi** [comment]
I’m working on a fix that removes the dependency on scikit-learn

**Comment by philipperemy** [comment]
@qwertpi thanks!
