### ISSUE TITLE
AtributeError when using on mobilenet transfer learned model

### ISSUE THREAD

**Issue by qwertpi** [philipperemy/keract#20]
When attempting to use keract to get the activations of a CNN given an image I get the error `AtributeError: Layer mobilenet_1.00_224 has multiple inbound nodes, hence the notion of "layer output" is ill-defined. Use get_output_at(node_index) instead`

Output of model.summary:
```
Layer (type)                 Output Shape              Param    
=================================================================
mobilenet_1.00_224 (Model)   (None, 7, 7, 1024)        3228864   
_________________________________________________________________
flatten_1 (Flatten)          (None, 50176)             0         
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 100354    
=================================================================
```
Full traceback:
```
Traceback (most recent call last):
  File "viz.py", line 43, in <module>
    activations = keract.get_activations(model, img)
  File "/usr/local/lib/python3.5/dist-packages/keract/keract.py", line 34, in get_activations
    nodes = [layer.output for layer in model.layers if layer.name == layer_name or layer_name is None]
  File "/usr/local/lib/python3.5/dist-packages/keract/keract.py", line 34, in <listcomp>
    nodes = [layer.output for layer in model.layers if layer.name == layer_name or layer_name is None]
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/base_layer.py", line 813, in output
    ' has multiple inbound nodes, '
AttributeError: Layer mobilenet_1.00_224 has multiple inbound nodes, hence the notion of "layer output" is ill-defined. Use `get_output_at(node_index)` instead.
```

Code defining model in my separate training code:
```
mn=mobilenet.MobileNet(weights='imagenet', include_top=False, input_shape=shape)

model = Sequential()
model.add(mn)
model.add(Flatten())
model.add(Dense(2, activation='softmax'))
```

**Comment by philipperemy** [comment]
@qwertpi thanks for raising the issue. Will have a look once I have some free time :)

**Comment by qwertpi** [comment]
I changed my code to be
```
cnn=model.layers[0]
cnn.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
activations = keract.get_activations(cnn, img)
```
instead of just
```
activations = keract.get_activations(model, img)
```
and now it works. I think this is beacuse the first layer is the entirety of the mobilenet model so layers[0] is a model in it's own right and that is the model that needs visualising

**Comment by philipperemy** [comment]
@qwertpi thanks for the input!
