### ISSUE TITLE
Keras Applications VGG16 has no attribute '_feed_targets'

### ISSUE THREAD

**Issue by tiagosamaha** [philipperemy/keract#23]
I'm trying to use transfer learning of VGG16, but when I run get_activations got AttributeError.

```
Traceback (most recent call last):
  File "rpn.py", line 16, in <module>
    activations = get_activations(feature_model, img_array)
  File "/home/tiago/.pyenv/versions/3.6.7/envs/mnist/lib/python3.6/site-packages/keract/keract.py", line 38, in get_activations
    activations = _evaluate(model, layer_outputs, x, y=None)
  File "/home/tiago/.pyenv/versions/3.6.7/envs/mnist/lib/python3.6/site-packages/keract/keract.py", line 6, in _evaluate
    symb_inputs = (model._feed_inputs + model._feed_targets + model._feed_sample_weights)
AttributeError: 'Model' object has no attribute '_feed_targets'
```

```
import numpy

from keras.applications import vgg16
from keras.preprocessing.image import load_img, img_to_array

from keract import get_activations, display_activations

img = load_img('eight.png')
img_array = img_to_array(img)
img_array = numpy.expand_dims(img_array, axis=0)

# last vgg16 conv2d layer returns (None, None, None, 512)
feature_model = vgg16.VGG16(include_top=False, input_shape=(600, 800, 3))
result = feature_model.predict(img_array)

activations = get_activations(feature_model, img_array)
display_activations(activations)
```

**Comment by philipperemy** [comment]
Oi Tiago,

I'll have a look! Thanks for reporting!

**Comment by tiagosamaha** [comment]
Hi Philippe!

In debugging I discovered that "_feed_targets" is assigned when compile/train the net. But with learning transfer this variable isn't set.

**Comment by philipperemy** [comment]
@tiagosamaha can you maybe compile your model before making inference? It's usually a good practice to do so.

**Comment by philipperemy** [comment]
I'm good to have a look in the case of transfer learning

**Comment by philipperemy** [comment]
```
import numpy
from keras.applications import vgg16
from keras.preprocessing.image import load_img, img_to_array

from keract import get_activations, display_activations

img = load_img('/Users/philipperemy/PycharmProjects/keract/eight.png')
img_array = img_to_array(img)
img_array = numpy.expand_dims(img_array, axis=0)

# last vgg16 conv2d layer returns (None, None, None, 512)
feature_model = vgg16.VGG16(include_top=False, input_shape=(512, 512, 3))
feature_model.compile(loss='categorical_crossentropy', optimizer='adam')        <-- Add this line.
result = feature_model.predict(img_array)

activations = get_activations(feature_model, img_array)
display_activations(activations)
```
That code works.

**Comment by philipperemy** [comment]
I could always compile the model in the library if not compiled but I guess it's safer to return an error saying model has to be compiled first. The loss somehow matters because it's used to compute the gradients. And Keract does not have any idea whatsoever of which loss was used to train the model. I guess here it's categorical cross entropy. Regarding the optimizer, it can be set to any random optimizer value (default is adam).

**Comment by philipperemy** [comment]
Something like this could be added:

```
if feature_model.name == 'vgg16':
    categorical_crossentropy', optimizer='adam')
else:
    raise Exception('Compile your model first.')
```

@tiagosamaha

**Comment by philipperemy** [comment]
Just for info I pushed a new code into master with what I discussed just above.

Feel free to try it.

```
pip install keract --upgrade
```

https://github.com/philipperemy/keract/pull/25/files

**Comment by philipperemy** [comment]
Merged https://github.com/philipperemy/keract/commit/83b2f573968920a10eab479f8c70db8299bf2733

**Comment by tiagosamaha** [comment]
It is an alternative. Compile will do nothing, but create the variables.

Thanks for your attention!
