### ISSUE TITLE
 TypeError: Invalid shape (1, 64, 64, 3) for image data

### ISSUE THREAD

**Issue by zeyzeyc** [philipperemy/keract#46]
Hi, i am new to keras applications. i try to display heatmaps but getting this error. 

Traceback (most recent call last):

  File "<ipython-input-13-7de1a703fa6f>", line 3, in <module>
    display_heatmaps(activations, image, save=False)

  File "C:\Users\ts1\Anaconda3\envs\tfenvnew\lib\site-packages\keract\keract.py", line 162, in display_heatmaps
    axes.flat[i].imshow(input_image / 255.0)

  File "C:\Users\ts1\Anaconda3\envs\tfenvnew\lib\site-packages\matplotlib\__init__.py", line 1589, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)

  File "C:\Users\ts1\Anaconda3\envs\tfenvnew\lib\site-packages\matplotlib\cbook\deprecation.py", line 369, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\ts1\Anaconda3\envs\tfenvnew\lib\site-packages\matplotlib\cbook\deprecation.py", line 369, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\ts1\Anaconda3\envs\tfenvnew\lib\site-packages\matplotlib\axes\_axes.py", line 5660, in imshow
    im.set_data(X)

  File "C:\Users\ts1\Anaconda3\envs\tfenvnew\lib\site-packages\matplotlib\image.py", line 683, in set_data
    .format(self._A.shape))

TypeError: Invalid shape (1, 64, 64, 3) for image data

**Comment by qwertpi** [comment]
matplotlib can't display your image as you've left the batch size in, use `image[0]` and your problem should be solved

**Comment by philipperemy** [comment]
Maybe we should add some additional checks and make the error more explicit here.

**Comment by qwertpi** [comment]
> Maybe we should add some additional checks and make the error more explicit here.

I've made a PR #49

**Comment by philipperemy** [comment]
@qwertpi awesome! You're so fast :)

**Comment by philipperemy** [comment]
2.6.1 released with the `fix` parameter

**Comment by qwertpi** [comment]
@zeyzeyc if you could download the new version of keract, verify it works, and then hopefully be able to close this issue then that would be great

**Comment by philipperemy** [comment]
@zeyzeyc I'm going to mark this issue as solved. Feel free to re-open the issue should you have any problems.
