### ISSUE TITLE
Error of placeholder tensor in _evaluate  function

### ISSUE THREAD

**Issue by jordangierschendorf** [philipperemy/keract#53]
Hi,
First, thanks for this great work !
I'm trying to use your repo but I have an error of placeholder shape in _evaluate function.

I have created a sequential model based-on VGG16 to perform binary classification:

`vgg_model = applications.VGG16(weights=None, include_top=False, input_shape=(224, 224, 3))`
`model = keras.models.Sequential()`
`model.add(vgg_model)`
`model.add(Flatten(input_shape=model.output_shape[1:]))`
`model.add(Dense(256, activation='relu'))`
`model.add(Dropout(0.75))`
`model.add(Dense(1, activation='sigmoid, name='Output_Classification'))`

I have no probleme during training and when I predict new data.

But when I want to visualize convolution filter I have an issue:

> Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.3\helpers\pydev\pydevd.py", line 1596, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.3\helpers\pydev\pydevd.py", line 974, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "//Nt-nas/2019/L'Oreal/MED/Etude/Codes/VGG16_VisualizeFeatureMap.py", line 178, in <module>
    keract.get_activations(model, img, layer_dict=layer_dict)
  File "C:\Python35\lib\site-packages\keract\keract.py", line 83, in get_activations
    activations = _evaluate(model, layer_outputs, x, y=None)
  File "C:\Python35\lib\site-packages\keract\keract.py", line 25, in _evaluate
    return f(x_ + y_ + sample_weight_)
  File "C:\Python35\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "C:\Python35\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "C:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1382, in __call__
    run_metadata_ptr)
  File "C:\Python35\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,224,224,3]
	 [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[?,224,224,3], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

The image I want to predict is the same as your vgg16.py file, so for me I think the shape is correct.

I used the following version:
keras 2.2.4
tensorflow 1.10.0
keract 2.6.2

Can you help me to fix it ?

**Comment by jordangierschendorf** [comment]
Hi again,

I solved my problem by changing my initial model definition to:

`vgg_model = applications.VGG16(weights=None, include_top=False, input_shape=(224, 224, 3))`
`model = keras.models.Sequential()`
`model.add(InputLayer(input_shape=(224, 224, 3)))`
`for layer in vgg_model.layers:
      model.add(layer)`
`model.add(Flatten(input_shape=model.output_shape[1:]))`
`model.add(Dense(256, activation='relu'))`
`model.add(Dropout(0.75))`
`model.add(Dense(1, activation='sigmoid', name='Output_Classification'))`

Then I loaded my initial weights and set it to my new "flat" vgg model, now it works !
